In [1]:
import pandas as pd
import json
import numpy as np

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,Unnamed: 0,title,text,latitude,longitude,city_text,date_posted,date_updated,price,deleted,...,bedrooms,bathrooms,pets,laundry,parking,craigslist,place,city,state,county
0,1,$895 / 1br - 500ft2 - 1 BD + 1 BD WATER PAID$ ...,QR Code Link to This Post\n \n ...,34.860788,-118.170104,W. ROSAMOND BLVD. / B ST.,2018-10-08 22:29:36,2018-10-15 13:07:37,895.0,False,...,1.0,1.0,none,shared,off-street,losangeles,Rosamond,NaN,CA,Kern
1,2,$895 / 1br - 500ft2 - 1 BD + 1 BD WATER PAID$ ...,QR Code Link to This Post\n \n ...,34.861017,-118.169932,W. ROSAMOND BLVD. / B ST.,2018-10-15 11:44:23,NaN,895.0,False,...,1.0,1.0,none,shared,off-street,losangeles,Rosamond,NaN,CA,Kern
2,3,$895 / 1br - 500ft2 - 1 BD + 1 BD WATER PAID$ ...,QR Code Link to This Post\n \n ...,34.861017,-118.169932,W. ROSAMOND BLVD. / B ST.,2018-10-15 11:53:06,NaN,895.0,False,...,1.0,1.0,none,shared,off-street,losangeles,Rosamond,NaN,CA,Kern
3,4,$895 / 1br - 500ft2 - 1 BD + 1 BD WATER PAID$ ...,QR Code Link to This Post\n \n ...,34.861017,-118.169932,W. ROSAMOND BLVD. / B ST.,2018-10-15 13:30:43,NaN,895.0,False,...,1.0,1.0,none,shared,off-street,losangeles,Rosamond,NaN,CA,Kern
4,5,$895 / 1br - 500ft2 - 1 BD + 1 BD WATER PAID$ ...,QR Code Link to This Post\n \n ...,34.860683,-118.169997,W. ROSAMOND BLVD. / B ST.,2018-10-15 13:36:07,NaN,895.0,False,...,1.0,1.0,none,shared,off-street,losangeles,Rosamond,NaN,CA,Kern

In [8]:
df[df.county=='San Francisco'].describe()

,Unnamed: 0,latitude,longitude,price,sqft,bedrooms,bathrooms
count,2894.000000,2894.000000,2894.000000,2891.000000,1160.000000,2721.000000,2721.000000
mean,20421.670352,37.776703,-122.428186,3675.764095,914.092241,1.319735,1.214627
std,1086.295202,0.019805,0.025506,1605.044289,490.289148,0.979914,0.506087
min,3533.000000,37.708232,-122.510248,0.000000,1.000000,0.000000,0.000000
25%,19720.250000,37.768996,-122.440511,2624.000000,623.750000,1.000000,1.000000
50%,20458.500000,37.781300,-122.422879,3459.000000,805.000000,1.000000,1.000000
75%,21203.500000,37.790434,-122.413011,4390.000000,1102.000000,2.000000,1.000000
max,21948.000000,37.823100,-122.368684,17700.000000,8933.000000,6.000000,5.000000

In [4]:
sf = df[df.county=='San Francisco']
sf.shape

(2894, 21)

In [5]:
sf['title'] = [title.split('\n')[0] for title in sf.title.values]
sf = sf.loc[sf.title.str.contains('\(')]
sf['neighborhood'] = [nh.split('(')[1][:-1] for nh in sf.title.values]
sf['title'] = [nh.split('(')[0] for nh in sf.title.values]

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [6]:
valid_neighborhoods = sf.neighborhood.value_counts()[sf.neighborhood.value_counts() > 4].index
valid_n = np.asarray([curr in valid_neighborhoods for curr in sf.neighborhood.values])
sf = sf.loc[valid_n]

In [13]:
sf['price_bucket'] = pd.qcut(sf.price, 4)

In [7]:
sf.shape

(2689, 22)

In [14]:
sf.to_csv('sf.csv', index=False)

In [14]:
sf.head(10).T

,3532,4554,9389,10433,10884,11494,12123,12396,12472,12809
Unnamed: 0,3533,4555,9390,10434,10885,11495,12124,12397,12473,12810
title,$2000 Are you looking for an AFFORDABLE home? ...,$5241 / 2br - 1095ft2 - Large Two Bedroom In G...,$7950 / 3br - 2030ft2 - 3 beds 3 baths Spaciou...,$1495 / 300ft2 - Happy and Restful Studio in S...,"$1400 Newly renovated apt. w/ balcony, granite...",$1645 Studio in Historic Pet-friendly Building...,$3750 / 2br - 850ft2 - Adorable two bedroom / ...,$3750 / 2br - Bright 2 bedroom unit ~ Newly re...,$3750 / 2br - 850ft2 - Completely remodeled 2 ...,$3750 / 2br - 850ft2 - Incredible 2 bedroom - ...
text,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...,QR Code Link to This Post\n \n ...
latitude,37.7749,37.7878,37.7621,37.738,37.7812,37.7813,37.7707,37.7707,37.7707,37.7707
longitude,-122.419,-122.393,-122.397,-122.409,-122.461,-122.417,-122.449,-122.449,-122.449,-122.449
city_text,NaN,"333 Fremont Street, San Francisco CA.",Potrero Hill,oakland west,/*san francisco*/,danville / san ramon,rohnert pk / cotati,rohnert pk / cotati,rohnert pk / cotati,rohnert pk / cotati
date_posted,2018-10-01 09:34:37,2018-10-06 16:25:41,2018-10-12 09:19:33,2018-09-28 06:39:14,2018-10-15 12:42:11,2018-10-01 14:38:01,2018-10-15 13:59:17,2018-10-09 13:49:06,2018-10-11 18:36:56,2018-10-08 10:11:32
date_updated,2018-10-14 11:26:18,2018-10-12 17:54:03,2018-10-15 08:18:26,2018-10-13 05:06:21,NaN,2018-10-15 09:49:21,NaN,NaN,NaN,NaN
price,2000,5241,7950,1495,1400,1645,3750,3750,3750,3750
deleted,False,False,False,False,False,False,False,False,False,False
sqft,NaN,1095,2030,300,NaN,NaN,850,NaN,850,850
bedrooms,NaN,2,3,0,NaN,0,2,2,2,2
bathrooms,NaN,2,3,1,NaN,1,1,1,1,1
pets,none,both,none,both,none,both,none,none,none,none
laundry,none,in-unit,NaN,shared,in-unit,shared,shared,shared,shared,shared
parking,none,garage,garage,none,none,none,none,none,none,none
craigslist,sacramento,sacramento,sfbay_eby,sfbay_eby,sfbay_eby,sfbay_eby,sfbay_nby,sfbay_nby,sfbay_nby,sfbay_nby
place,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco
city,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco
state,CA,CA,CA,CA,CA,CA,CA,CA,CA,CA
county,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco,San Francisco

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.